/*
 * This file is part of the ThOR project: http://3dorus.ist.utl.pt/tools/thor
 * ThOR is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * ThOR is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * 
 * We kindly ask you to refer the any or one of the following publications in
 * any publication mentioning or employing ThOR:
 * 
 * Pedro B. Pascoal and Alfredo Ferreira. 8th Eurographics Workshop on 3D Object Retrieval,
 * Zurich, Switzerland, May 2-3, 2015
 * 
 * Copyright statement:
 * ====================
 * (c) 2011-2015 by Pedro B. Pascoal (pmbp@tecnico.ulisboa.pt)
 * http://3dorus.ist.utl.pt/tools/thor, https://web.ist.utl.pt/pmbp/projects/thor
 */
package thor.modelanalysis.lfd;

import java.util.ArrayList;

import thor.Model;
import thor.model.BufferedModel;
import thor.model.geoset.BufferedMesh;

/**
 * This file was autogenerated using the ModelConverter from the ThOR project.

 * Original File: dodecahedron_7.off
 * Original Format: off
 * 
 * Model Name: dodecahedron_7
 * Vertices: 20
 * Faces: 20

 * @author ThOR-ModelConverter
 */
class dodecahedron_7 {

	@SuppressWarnings("serial")
	public static Model createModel() {
		BufferedModel model = new BufferedModel("dodecahedron_7", "java");
		BufferedMesh mesh = new BufferedMesh();

		// Add list of vertices:
		mesh.addVertex(0.264391f,-1.037088f,-0.021073f);
		mesh.addVertex(-0.493469f,-0.948192f,-0.057552f);
		mesh.addVertex(-0.651797f,-0.520845f,-0.670655f);
		mesh.addVertex(0.008218f,-0.345625f,-1.013098f);
		mesh.addVertex(0.574455f,-0.664675f,-0.611642f);
		mesh.addVertex(1.011906f,-0.103555f,-0.333486f);
		mesh.addVertex(0.972243f,-0.129183f,0.42899f);
		mesh.addVertex(0.51022f,-0.706122f,0.62206f);
		mesh.addVertex(-0.095718f,-0.412688f,0.983069f);
		mesh.addVertex(-0.716033f,-0.562292f,0.563047f);
		mesh.addVertex(-1.011906f,0.103555f,0.333486f);
		mesh.addVertex(-0.972243f,0.129183f,-0.42899f);
		mesh.addVertex(-0.51022f,0.706122f,-0.62206f);
		mesh.addVertex(0.095718f,0.412688f,-0.983069f);
		mesh.addVertex(0.716033f,0.562292f,-0.563047f);
		mesh.addVertex(0.651797f,0.520845f,0.670655f);
		mesh.addVertex(-0.008218f,0.345625f,1.013098f);
		mesh.addVertex(-0.574455f,0.664675f,0.611642f);
		mesh.addVertex(-0.264391f,1.037088f,0.021073f);
		mesh.addVertex(0.493469f,0.948192f,0.057552f);

		// Add list of faces:
		mesh.addFace(new ArrayList<Integer>() {{add(15);add(16);add(17);}});
		mesh.addFace(new ArrayList<Integer>() {{add(19);add(15);add(17);}});
		mesh.addFace(new ArrayList<Integer>() {{add(19);add(17);add(18);}});
		mesh.addFace(new ArrayList<Integer>() {{add(6);add(15);add(19);}});
		mesh.addFace(new ArrayList<Integer>() {{add(5);add(6);add(19);}});
		mesh.addFace(new ArrayList<Integer>() {{add(5);add(19);add(14);}});
		mesh.addFace(new ArrayList<Integer>() {{add(14);add(19);add(18);}});
		mesh.addFace(new ArrayList<Integer>() {{add(14);add(18);add(12);}});
		mesh.addFace(new ArrayList<Integer>() {{add(13);add(14);add(12);}});
		mesh.addFace(new ArrayList<Integer>() {{add(18);add(17);add(10);}});
		mesh.addFace(new ArrayList<Integer>() {{add(18);add(10);add(11);}});
		mesh.addFace(new ArrayList<Integer>() {{add(12);add(18);add(11);}});
		mesh.addFace(new ArrayList<Integer>() {{add(10);add(17);add(16);}});
		mesh.addFace(new ArrayList<Integer>() {{add(10);add(16);add(8);}});
		mesh.addFace(new ArrayList<Integer>() {{add(9);add(10);add(8);}});
		mesh.addFace(new ArrayList<Integer>() {{add(16);add(15);add(6);}});
		mesh.addFace(new ArrayList<Integer>() {{add(8);add(16);add(6);}});
		mesh.addFace(new ArrayList<Integer>() {{add(8);add(6);add(7);}});
		mesh.addFace(new ArrayList<Integer>() {{add(5);add(14);add(13);}});
		mesh.addFace(new ArrayList<Integer>() {{add(5);add(13);add(3);}});
		mesh.addFace(new ArrayList<Integer>() {{add(4);add(5);add(3);}});
		mesh.addFace(new ArrayList<Integer>() {{add(13);add(12);add(11);}});
		mesh.addFace(new ArrayList<Integer>() {{add(3);add(13);add(11);}});
		mesh.addFace(new ArrayList<Integer>() {{add(3);add(11);add(2);}});
		mesh.addFace(new ArrayList<Integer>() {{add(10);add(9);add(1);}});
		mesh.addFace(new ArrayList<Integer>() {{add(11);add(10);add(1);}});
		mesh.addFace(new ArrayList<Integer>() {{add(11);add(1);add(2);}});
		mesh.addFace(new ArrayList<Integer>() {{add(9);add(8);add(7);}});
		mesh.addFace(new ArrayList<Integer>() {{add(9);add(7);add(0);}});
		mesh.addFace(new ArrayList<Integer>() {{add(1);add(9);add(0);}});
		mesh.addFace(new ArrayList<Integer>() {{add(6);add(0);add(7);}});
		mesh.addFace(new ArrayList<Integer>() {{add(5);add(0);add(6);}});
		mesh.addFace(new ArrayList<Integer>() {{add(4);add(0);add(5);}});
		mesh.addFace(new ArrayList<Integer>() {{add(1);add(0);add(4);}});
		mesh.addFace(new ArrayList<Integer>() {{add(2);add(1);add(4);}});
		mesh.addFace(new ArrayList<Integer>() {{add(2);add(4);add(3);}});

		// Add built mesh:
		model.addMesh(mesh);
		return model;
	}
}
